/*
 * rust test
 *
 * rust name mapping test
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropertyNameMapping {
    #[serde(rename = "http_debug_operation", skip_serializing_if = "Option::is_none")]
    pub http_debug_operation: Option<String>,
    #[serde(rename = "_type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "type_", skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    #[serde(rename = "-type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl PropertyNameMapping {
    pub fn new() -> PropertyNameMapping {
        PropertyNameMapping {
            http_debug_operation: None,
            _type: None,
            r#type: None,
            type_: None,
            _type: None,
        }
    }
}


