# #OpenAPI Petstore
#
##This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 7.0.0-SNAPSHOT
#

require "uri"

module Petstore
  class FakeApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # parameter name mapping test
    # @param _type [Int64] _type
    # @param _type2 [String] type
    # @param type_ [String] type_
    # @param type_2 [String] type-
    # @param http_debug_option [String] http debug option (to test parameter naming option)
    # @return [nil]
    def get_parameter_name_mapping(_type : Int64, _type2 : String, type_ : String, type_2 : String, http_debug_option : String)
      get_parameter_name_mapping_with_http_info(_type, _type2, type_, type_2, http_debug_option)
      nil
    end

    # parameter name mapping test
    # @param _type [Int64] _type
    # @param _type2 [String] type
    # @param type_ [String] type_
    # @param type_2 [String] type-
    # @param http_debug_option [String] http debug option (to test parameter naming option)
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def get_parameter_name_mapping_with_http_info(_type : Int64, _type2 : String, type_ : String, type_2 : String, http_debug_option : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: FakeApi.get_parameter_name_mapping ..."}
      end
      # verify the required parameter "_type" is set
      if @api_client.config.client_side_validation && _type.nil?
        raise ArgumentError.new("Missing the required parameter '_type' when calling FakeApi.get_parameter_name_mapping")
      end
      # verify the required parameter "_type2" is set
      if @api_client.config.client_side_validation && _type2.nil?
        raise ArgumentError.new("Missing the required parameter '_type2' when calling FakeApi.get_parameter_name_mapping")
      end
      # verify the required parameter "type_" is set
      if @api_client.config.client_side_validation && type_.nil?
        raise ArgumentError.new("Missing the required parameter 'type_' when calling FakeApi.get_parameter_name_mapping")
      end
      # verify the required parameter "type_2" is set
      if @api_client.config.client_side_validation && type_2.nil?
        raise ArgumentError.new("Missing the required parameter 'type_2' when calling FakeApi.get_parameter_name_mapping")
      end
      # verify the required parameter "http_debug_option" is set
      if @api_client.config.client_side_validation && http_debug_option.nil?
        raise ArgumentError.new("Missing the required parameter 'http_debug_option' when calling FakeApi.get_parameter_name_mapping")
      end
      # resource path
      local_var_path = "/fake/parameter-name-mapping"

      # query parameters
      query_params = Hash(String, String).new
      query_params["type"] = _type2.to_s unless _type2.nil?
      query_params["http_debug_option"] = http_debug_option.to_s unless http_debug_option.nil?

      # header parameters
      header_params = Hash(String, String).new
      header_params["_type"] = _type
      header_params["type_"] = type_
      header_params["type-"] = type_2

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"FakeApi.get_parameter_name_mapping",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: FakeApi#get_parameter_name_mapping\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
